# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-31 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, max_length=500)),
                ('ubicacion', models.CharField(blank=True, max_length=30)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('confirmar_email', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productobase',
            name='opciones_cobro',
            field=models.CharField(choices=[('estandar', 'Precio est\xe1ndar'), ('personalizado', 'Personalizado'), ('por_docena', 'Por docena')], max_length=100),
        ),
    ]
