# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20171031_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recaudo',
            name='recibido',
        ),
        migrations.RemoveField(
            model_name='recibido',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='producto',
            name='recibido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Recibido'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Recaudo',
        ),
        migrations.DeleteModel(
            name='Recibido',
        ),
    ]
